python main.py --log-dir ./logs/our_diva_bce/1000 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=4200000|model.aux_loss_multiplier_d=2000000|model.beta_d=1000|model.beta_x=1000|model.beta_y=1000" &
python main.py --log-dir ./logs/our_diva_bce/100 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=420000|model.aux_loss_multiplier_d=200000|model.beta_d=100|model.beta_x=100|model.beta_y=100" &
python main.py --log-dir ./logs/our_diva_bce/50 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=210000|model.aux_loss_multiplier_d=100000|model.beta_d=50|model.beta_x=50|model.beta_y=50"
python main.py --log-dir ./logs/our_diva_bce/10 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=42000|model.aux_loss_multiplier_d=20000|model.beta_d=10|model.beta_x=10|model.beta_y=10" &
python main.py --log-dir ./logs/our_diva_bce/5 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=21000|model.aux_loss_multiplier_d=10000|model.beta_d=5|model.beta_x=5|model.beta_y=5" &
python main.py --log-dir ./logs/our_diva_bce/2 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=8400|model.aux_loss_multiplier_d=4000|model.beta_d=2|model.beta_x=2|model.beta_y=2"
python main.py --log-dir ./logs/our_diva_bce/1 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=4200|model.aux_loss_multiplier_d=2000|model.beta_d=1|model.beta_x=1|model.beta_y=1" &
python main.py --log-dir ./logs/our_diva_bce/_5 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=2100|model.aux_loss_multiplier_d=1000|model.beta_d=0.5|model.beta_x=0.5|model.beta_y=0.5" &
python main.py --log-dir ./logs/our_diva_bce/_2 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=840|model.aux_loss_multiplier_d=400|model.beta_d=0.2|model.beta_x=0.2|model.beta_y=0.2"
python main.py --log-dir ./logs/our_diva_bce/_125 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=525|model.aux_loss_multiplier_d=250|model.beta_d=0.125|model.beta_x=0.125|model.beta_y=0.125" &
python main.py --log-dir ./logs/our_diva_bce/_11 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=467|model.aux_loss_multiplier_d=222|model.beta_d=0.11|model.beta_x=0.11|model.beta_y=0.11" &
python main.py --log-dir ./logs/our_diva_bce/_1 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=420|model.aux_loss_multiplier_d=200|model.beta_d=0.1|model.beta_x=0.1|model.beta_y=0.1"
python main.py --log-dir ./logs/our_diva_bce/_02 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=84|model.aux_loss_multiplier_d=40|model.beta_d=0.02|model.beta_x=0.02|model.beta_y=0.02" &
python main.py --log-dir ./logs/our_diva_bce/_01 --config configs/ourdiva.yaml --episode episodes/diva_experiment/diva_unsupervised_boost.yaml --override "model.aux_loss_multiplier_y=42|model.aux_loss_multiplier_d=20|model.beta_d=0.01|model.beta_x=0.01|model.beta_y=0.01"




