###########
# Dataset #
###########

data_root: 'data_files'
batch_size: 50
num_workers: 4
eval_batch_size: 100
eval_num_workers: 4

label_offset:
  mnist: 0
  svhn: 0
  usps: 0

#########
# Model #
#########

x_c: 1
x_h: 28
x_w: 28
y_c: 10

device: 'cuda'
testing_mode: True
model_name: 'diva'
recon_loss: 'gaussian'

###########
# Summary #
###########

add_time_to_log: False
summary_step: 100
eval_step: 600
summarize_samples: True
initial_evaluation: False
training_loss_step: 100

##########
# Replay #
##########
replay_batch_size: 100
replay_ratio: 1
replay_loss_multiplier: 1


################
# DIVA configs #
################
diva:
  # Training settings
  description: 'TwoTaskVae'
  no-cuda: False
  seed: 0
  batch-size: 100
  epochs: 500
  lr: 0.001
  num-supervised: 1000

  # Model
  d_dim: 6
  x_dim: 784
  y_dim: 10
  zd_dim: 64
  zx_dim: 64
  zy_dim: 64

  # Aux multipliers
  aux_loss_multiplier_y: 3500
  aux_loss_multiplier_d: 2000

  # Beta VAE part
  beta_d: 1
  beta_x: 1
  beta_y: 1
#
# w, warm_up, N: 100
#  max_beta, MB: 1    help='max beta for warm-up')
#  min_beta, MB: 0    help='min beta for warm-up')
#
#  # Set seed
#  torch.manual_seed(args.seed)
#  torch.backends.cudnn.benchmark = False
#  np.random.seed(args.seed)
